apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employees
        image: tzvitsuryev/employees:alpine
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: employees-srv
spec:
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
